### ISSUE TITLE
Just saying thanks :)

### ISSUE THREAD

**Issue by tjdevries** [ccchapman/dotfiles#15]
Hey, just wanted to say thanks for the sponsor :) didn't know how else to reach out :laughing: 

-TJ

**Comment by ccchapman** [comment]
Thank you for all of your contributions to the community. It is so exciting to see the direction everything is headed, and I really appreciate your influence on it.

It seems to me that things are also more approachable and easier for new users to setup. I am very happy to be porting my configuration over to the built-in LSP, Telescope, and `init.lua`. Compared to numerous past attempts, this time around has been trouble free.
